title: "kitecreature.net"
baseurl: ""
url: "https://kitecreature.net"
include: [_pages]
sass:
  style: compressed
plugins:
  - jekyll-redirect-from
  - jekyll-coffeescript
exclude:
  - _pages/halloween
  - assets/godot/halloweenbowl
